### ISSUE TITLE
Question about networking

### ISSUE THREAD

**Issue by ebuildy** [sameersbn/docker-apt-cacher-ng#3]
Hello,

I see you have hardcoded ip "172.17.42.1", is it possible to have a more generic solution instead?

I don't find documentation about network when building an image.

Thanks you,

**Comment by sameersbn** [comment]
@ebuildy the `172.17.42.1` is only an example (should be updated to 172.17.0.1) to use on the same host as the container. If you want the service to be accessible from the local network you should be able to set the correct ip and it should work since we are binding to all interfaces with `--publish 3142:3142`
